[tool.poetry]
name = "ingest-pyneoinstance"
version = "0.1.0"
description = ""
authors = ["Henry Lin <henry.lin@neo4j.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.2"
pyneoinstance = "^2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
